### ISSUE TITLE
Shovel doesn't work in latest version 

### ISSUE THREAD

**Issue by Myndnix** [ShadowOne333/A-Link-to-the-Past-Redux#15] opened 2023-03-29 10:24 UTC
My friend and I are playing your hack on two different emulators (I'm using Mednafen v1.29.0, they're using Retroarch v1.9 with the bsnes-mercury core but also tried SNES9X v1.61 core). The shovelling minigame worked as intended, but when we attempted to get the Ocarina, the Shovel given by the kid simply doesn't work, no matter what we tried. 
I'm using several of the optional patches, but my friend isn't using any. We both patched the correct ROM version, including verifying the hash.
Is there something we're missing? It seems like a bug to us. We've hard reset and everything.

**Comment by ShadowOne333** [comment] 2023-03-29 17:38
What happens when you try to get the ocarina?

**Comment by Myndnix** [comment] 2023-03-29 17:58
We can't get it due to being unable to use the Shovel. We can select the Shovel from the menu, but the Y button does nothing when it's equipped. I assume you still dig up the Ocarina in this hack?

**Comment by Myndnix** [comment] 2023-03-30 21:29
We bypassed it by using PAR code 7EF34C02, which my friend mined from the vanilla ROM. This forced the Ocarina into the inventory, fully functional. The Shovel, however, still doesn't work at all.

**Comment by ShadowOne333** [comment] 2023-03-31 04:40
I did some debugging and found out the issue is with this file specifically:
https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/blob/main/code/menus/24items_menu_shovel.asm

Commenting out that file in the code makes the Shovel work. However, I haven't been able to figure out why exactly the shovel is failing within the code in that file. I'll try debugging some more to find the issue, it should be fixed within this week.

**Comment by ShadowOne333** [comment] 2023-03-31 17:07
I think I found the issue, it was a BNE (branch if not equal), but one line after where it should be.
Could you try out this patch and let me know if the Shovel works properly now, please?
https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/blob/main/patches/Link%20to%20the%20Past%20Redux.ips

**Comment by Myndnix** [comment] 2023-03-31 19:28
My friend tested it, and it works! Fantastic work!

**Comment by ShadySalesGnome** [comment] 2023-03-31 19:34
just tried it out, the shovel is working, but now I can't seem to save.

**Comment by ShadowOne333** [comment] 2023-03-31 19:53
> just tried it out, the shovel is working, but now I can't seem to save.
> 
> Edit: or maybe I can but the text is just wrong, can't tell for sure.

Do you have a pic of that?

**Comment by ShadySalesGnome** [comment] 2023-03-31 20:20
![Screenshot (77)](https://user-images.githubusercontent.com/73858930/229220560-efd85930-2568-4c59-8f81-f510dbd54a56.png)
I have used save states before, but this is occurring when I load the game normaly, and for some reason when I talk to the digging game guy it gives the continue game, and the save and quit options, it doesn't actually save but depending on which I choose it starts the digging game
![Screenshot (78)](https://user-images.githubusercontent.com/73858930/229221428-7a9a992f-0f65-48d6-b0f0-ca7ebbe4be87.png)
I do have one of the optional patches on, it's the green agahnim patch.

**Comment by ShadowOne333** [comment] 2023-03-31 20:24
That's weird, I just tried booting up a fresh game with the latest patch I pushed, and I get the normal text for that guy.
I also tried with the Green Agahnim patch and it works as intended on my end.

Can you try with this patch?
https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/blob/main/patches/Link%20to%20the%20Past%20Redux.ips

**Comment by ShadySalesGnome** [comment] 2023-03-31 20:28
fixed it somehow, I'm not really sure what happened, did a fresh patch and everything is working now, tested with snes9x and bsnes,

**Comment by ShadowOne333** [comment] 2023-03-31 20:45
Oh good to know, glad you got it working too.
I'll go ahead and close this issue up then, thanks for bringing this to my attention.

**Closed by ShadowOne333** 2023-03-31 20:45 UTC

**Comment by chrcoluk** [comment] 2024-08-29 02:18
Hi, I noticed the date of these fixes is newer than the latest version on the site, and you didnt do a patched ips for the retranslation, can you please clarify if I use the latest retranslation patch the shovel fix is in place?

Thanks.
