### ISSUE TITLE
Swamp Palace Locked Door re-appearing

### ISSUE THREAD

**Issue by Kirizame55** [ShadowOne333/A-Link-to-the-Past-Redux#2] opened 2022-08-22 00:00 UTC
Emulator: Snes9x 1.60

Patches I had installed:
Re-Translation
Kakariko Shortcut
Mirror Works in Both Worlds
Remove Low Health Beep
Start at Full Hearts
Triforce of the Gods Subtitle

Unsure what specifically caused this but it happened twice.
I was doing a playthrough where I was messing around with the Mirror working in both worlds, using it to get a few things before the first fight with Agahnim.

First time was:
Enter Swamp Palace
Get up to the mole things (forgot I needed the Hammer)
Leave
Get the Hammer from Dark Palace
Return to Swamp Palace
First locked door has re-appeared, making the dungeon impossible

I then used a PAR code to give myself 9 keys as I didn't fancy replaying the game to that point and got the Hookshot, leaving the dungeon early.
Sure enough after I had fought Agahnim the Locked Door reappeared again. 

This didn't seem to affect any other dungeon as I had previously used the Mirror to enter Turtle Rock and Dark Palace and all of the locked doors I had opened stayed open.

If it matters somehow, my method of entering the Palace was draining the water then using the Mirror as I left the Light World entrance.

**Comment by ShadowOne333** [comment] 2022-08-23 19:06
Found the culprit of the issue I believe.
You can even trigger by exiting the Dungeon, leave to one screen right, and return, and then you have to redo the water gate puzzle and once you enter the Swamp Palace again, the door is shut again while the chest remains open.

I tried several combinations, and the only one that seems to be triggering it is by patching the "Triforce of the Gods" subtitle patch.
For testing purposes, can you two things?

1. Try doing one test with all the same patches except the Subtitle patch
2. Try it again with the Subtitle patch added in to see if that one alone is indeed the one causing it

Thanks for bringing this up.

**Comment by ShadowOne333** [comment] 2022-08-25 20:05
I confirmed it was the Subtitle patches that caused this.
It was due to an LDA in 0x00CBA0 that was being modified to who-knows what address.
It is supposed to be LDA $7EF051 in the original, and it should still be.

This was caused due to Hyrule Magic somehow modifying that LDA to something like LDA $F1CD51 whenever you attempt to modify the Title Screen at all (which happened due to modifying the BG2 tiles for the new Subtitle). Not sure why Hyrule Magic even modifies dungeon data when all you do is just change the title screen, but oh well.

This has been fixed in the latest commits, so now patching the Subtitle hacks shouldn't cause this anymore.

**Closed by ShadowOne333** 2022-08-25 20:05 UTC
